// Generated from etc/input.conf

"# mpv keybindings\n"
"#\n"
"# Location of user-defined bindings: ~/.config/mpv/input.conf\n"
"#\n"
"# Lines starting with # are comments. Use SHARP to assign the # key.\n"
"# Copy this file and uncomment and edit the bindings you want to change.\n"
"#\n"
"# List of commands and further details: DOCS/man/input.rst\n"
"# List of special keys: --input-keylist\n"
"# Keybindings testing mode: mpv --input-test --force-window --idle\n"
"#\n"
"# Use 'ignore' to unbind a key fully (e.g. 'ctrl+a ignore').\n"
"#\n"
"# Strings need to be quoted and escaped:\n"
"#   KEY show-text \"This is a single backslash: \\\\ and a quote: \\\" !\"\n"
"#\n"
"# You can use modifier-key combinations like Shift+Left or Ctrl+Alt+x with\n"
"# the modifiers Shift, Ctrl, Alt and Meta (may not work on the terminal).\n"
"#\n"
"# The default keybindings are hardcoded into the mpv binary.\n"
"# You can disable them completely with: --no-input-default-bindings\n"
"\n"
"# Developer note:\n"
"# On compilation, this file is baked into the mpv binary, and all lines are\n"
"# uncommented (unless '#' is followed by a space) - thus this file defines the\n"
"# default key bindings.\n"
"\n"
"# If this is enabled, treat all the following bindings as default.\n"
"#default-bindings start\n"
"\n"
"#MBTN_LEFT     ignore              # don't do anything\n"
"#MBTN_LEFT_DBL cycle fullscreen    # toggle fullscreen on/off\n"
"#MBTN_RIGHT    cycle pause         # toggle pause on/off\n"
"\n"
"# Mouse wheels, touchpad or other input devices that have axes\n"
"# if the input devices supports precise scrolling it will also scale the\n"
"# numeric value accordingly\n"
"#WHEEL_UP      seek 10\n"
"#WHEEL_DOWN    seek -10\n"
"#WHEEL_LEFT    add volume -2\n"
"#WHEEL_RIGHT   add volume 2\n"
"\n"
"## Seek units are in seconds, but note that these are limited by keyframes\n"
"#RIGHT seek  5\n"
"#LEFT  seek -5\n"
"#UP    seek  60\n"
"#DOWN  seek -60\n"
"# Do smaller, always exact (non-keyframe-limited), seeks with shift.\n"
"# Don't show them on the OSD (no-osd).\n"
"#Shift+RIGHT no-osd seek  1 exact\n"
"#Shift+LEFT  no-osd seek -1 exact\n"
"#Shift+UP    no-osd seek  5 exact\n"
"#Shift+DOWN  no-osd seek -5 exact\n"
"#PGUP add chapter 1                     # skip to next chapter\n"
"#PGDWN add chapter -1                   # skip to previous chapter\n"
"#Shift+PGUP seek 600\n"
"#Shift+PGDWN seek -600\n"
"#[ multiply speed 1/1.1                 # scale playback speed\n"
"#] multiply speed 1.1\n"
"#{ multiply speed 0.5\n"
"#} multiply speed 2.0\n"
"#BS set speed 1.0                       # reset speed to normal\n"
"#Shift+BS revert-seek                   # undo previous (or marked) seek\n"
"#Shift+Ctrl+BS revert-seek mark         # mark position for revert-seek\n"
"#q quit\n"
"#Q quit-watch-later\n"
"#q {encode} quit 4\n"
"#ESC set fullscreen no\n"
"#ESC {encode} quit 4\n"
"#p cycle pause                          # toggle pause/playback mode\n"
"#. frame-step                           # advance one frame and pause\n"
"#, frame-back-step                      # go back by one frame and pause\n"
"#SPACE cycle pause\n"
"#> playlist-next                        # skip to next file\n"
"#ENTER playlist-next                    # skip to next file\n"
"#< playlist-prev                        # skip to previous file\n"
"#9 add volume -2\n"
"#/ add volume -2\n"
"#0 add volume 2\n"
"#* add volume 2\n"
"#m cycle mute\n"
"#FORWARD seek 60\n"
"#REWIND seek -60\n"
"#NEXT playlist-next\n"
"#PREV playlist-prev\n"
"#VOLUME_UP add volume 2\n"
"#VOLUME_DOWN add volume -2\n"
"#MUTE cycle mute\n"
"#l ab-loop                              # Set/clear A-B loop points\n"
"#L cycle-values loop-file \"inf\" \"no\"    # toggle infinite looping\n"
"#ctrl+c quit 4\n"
"#F8 show_text \044{playlist}               # show playlist\n"
"#F9 show_text \044{track-list}             # show list of audio/sub streams\n"
"\n"
"#\n"
"# Legacy bindings (may or may not be removed in the future)\n"
"#\n"
"#! add chapter -1                       # skip to previous chapter\n"
"#\100 add chapter 1                        #         next\n"
"\n"
"#\n"
"# Not assigned by default\n"
"# (not an exhaustive list of unbound commands)\n"
"#\n"
"\n"
"# ? cycle program                       # cycle transport stream programs\n"
"# ? stop                                # stop playback (quit or enter idle mode)\n"
